version: "0.1"
services:
  storage:
    container_name: "db_storage"
    image: postgres:16.0
    env_file:
      - ./default.env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - net1

  gendataapp:
    build:
      context: ./gen_app
    image: mdb_genapp
    env_file:
      - ./default.env
    volumes:
      - ./gen_app/app:/apps
    depends_on:
      - storage
    deploy:
        replicas: 3
    networks:
      - net1

  visapp:
    container_name: "vis_app"
    build:
      context: ./vis_app
    image: mdb_visapp
    env_file:
      - ./default.env
    ports:
      - "8501:8501"
      - "8502:8502"
      - "8503:8503"
      - "8504:8504"
    volumes:
      - ./vis_app/app:/app
    depends_on:
      - storage
    networks:
      - net1

networks:
  net1:
    driver: bridge
